# Generated by Django 4.2.5 on 2023-12-04 05:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member_Project_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=0)),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField()),
                ('date_ended', models.DateTimeField()),
                ('task_status', models.BooleanField(default=0)),
                ('task_description', models.CharField(default='NA', max_length=1000)),
                ('task_title', models.CharField(default='NA', max_length=100)),
                ('emp_id_assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.member_project_status')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proj_name', models.CharField(max_length=100)),
                ('proj_status', models.CharField(max_length=10)),
                ('proj_startdate', models.DateField()),
                ('proj_enddate', models.DateField()),
                ('proj_desc', models.CharField(default='NA', max_length=1000)),
                ('proj_lead_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proj_lead_id', to=settings.AUTH_USER_MODEL)),
                ('proj_mgr_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proj_man_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='member_project_status',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.project'),
        ),
    ]
