# Generated by Django 4.2.3 on 2023-10-04 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="proj_desc",
            field=models.CharField(default="NA", max_length=1000),
        ),
        migrations.AddField(
            model_name="tasks",
            name="task_description",
            field=models.CharField(default="NA", max_length=1000),
        ),
        migrations.AddField(
            model_name="tasks",
            name="task_status",
            field=models.CharField(default="NA", max_length=10),
        ),
        migrations.AddField(
            model_name="tasks",
            name="task_title",
            field=models.CharField(default="NA", max_length=100),
        ),
        migrations.AddField(
            model_name="tasks",
            name="updated_enddate",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="tasks",
            name="updated_startdate",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="proj_enddate",
            field=models.DateField(default=django.db.models.deletion.SET_NULL),
        ),
        migrations.AlterField(
            model_name="project",
            name="proj_startdate",
            field=models.DateField(default=django.db.models.deletion.SET_NULL),
        ),
        migrations.AlterField(
            model_name="tasks",
            name="emp_id_assigned_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="manager_id",
                to="manager.userprofile",
            ),
        ),
    ]
