# Generated by Django 4.2.4 on 2023-09-06 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0002_project_proj_desc"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasks",
            name="task_status",
            field=models.CharField(default="NA", max_length=10),
        ),
    ]
