# Generated by Django 4.2.4 on 2023-12-02 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0002_project_proj_desc_tasks_task_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project", name="proj_enddate", field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="project", name="proj_startdate", field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="tasks",
            name="updated_enddate",
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name="tasks",
            name="updated_startdate",
            field=models.DateField(default=None),
        ),
        migrations.DeleteModel(name="Members",),
    ]
