# Generated by Django 4.2.4 on 2023-12-03 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0003_alter_project_proj_enddate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasks",
            name="task_status",
            field=models.BooleanField(default=0),
        ),
        migrations.CreateModel(
            name="Member_Project_Status",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.BooleanField(default=0)),
                ("date_joined", models.DateField(auto_now_add=True)),
                (
                    "emp_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="manager.userprofile",
                    ),
                ),
                (
                    "project_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="manager.project",
                    ),
                ),
            ],
        ),
    ]
