# Generated by Django 4.2.4 on 2023-09-06 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0003_tasks_task_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasks",
            name="task_description",
            field=models.CharField(default="NA", max_length=1000),
        ),
        migrations.AddField(
            model_name="tasks",
            name="task_title",
            field=models.CharField(default="NA", max_length=100),
        ),
    ]
