# Generated by Django 4.2.4 on 2023-09-11 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0004_tasks_task_description_tasks_task_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasks",
            name="updated_enddate",
            field=models.DateTimeField(default="NA"),
        ),
        migrations.AddField(
            model_name="tasks",
            name="updated_startdate",
            field=models.DateTimeField(default="NA"),
        ),
    ]
