# Generated by Django 4.2.4 on 2023-09-11 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0005_tasks_updated_enddate_tasks_updated_startdate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasks",
            name="updated_enddate",
            field=models.DateTimeField(default=django.db.models.deletion.SET_NULL),
        ),
        migrations.AlterField(
            model_name="tasks",
            name="updated_startdate",
            field=models.DateTimeField(default=django.db.models.deletion.SET_NULL),
        ),
    ]
