# Generated by Django 4.2.4 on 2023-12-03 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0005_alter_member_project_status_emp_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="proj_updated_end_date",
        ),
        migrations.RemoveField(
            model_name="project",
            name="proj_updated_start_date",
        ),
    ]
