# Generated by Django 4.2.4 on 2023-12-03 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0006_remove_project_proj_updated_end_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="proj_client",
        ),
    ]
