# Generated by Django 4.2.4 on 2023-12-03 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("manager", "0007_remove_project_proj_client"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tasks",
            name="emp_id_assigned_by",
        ),
        migrations.AlterField(
            model_name="tasks",
            name="emp_id_assigned_to",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
