# Generated by Django 4.2.4 on 2023-09-11 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0007_alter_tasks_updated_enddate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasks",
            name="emp_id_assigned_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="manager_id",
                to="manager.userprofile",
            ),
        ),
        migrations.AlterField(
            model_name="tasks",
            name="updated_enddate",
            field=models.DateTimeField(default=django.db.models.deletion.SET_DEFAULT),
        ),
        migrations.AlterField(
            model_name="tasks",
            name="updated_startdate",
            field=models.DateTimeField(default=django.db.models.deletion.SET_DEFAULT),
        ),
    ]
