# Generated by Django 4.2.4 on 2023-12-03 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0008_remove_tasks_emp_id_assigned_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasks",
            name="emp_id_assigned_to",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="manager.member_project_status",
            ),
        ),
    ]
