# Generated by Django 4.2.4 on 2023-12-03 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0009_alter_tasks_emp_id_assigned_to"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tasks",
            name="updated_enddate",
        ),
        migrations.RemoveField(
            model_name="tasks",
            name="updated_startdate",
        ),
    ]
