# Generated by Django 4.2.4 on 2023-09-12 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0009_alter_tasks_updated_enddate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasks",
            name="updated_enddate",
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name="tasks",
            name="updated_startdate",
            field=models.DateField(default=None),
        ),
    ]
