# Generated by Django 4.2.4 on 2023-12-04 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0010_remove_tasks_updated_enddate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasks",
            name="task_status",
            field=models.IntegerField(default=0),
        ),
    ]
